Update mesh-api.yaml re. open source
NHSDigital/mesh-api-specification pull request #108
Opened 2023-06-21 17:10 UTC by tonyheap

added details of open source assets

## Summary
* Routine Change
* :exclamation: Breaking Change
* :robot: Operational or Infrastructure Change
* :sparkles: New Feature
* :warning: Potential issues that might be caused by this change

Add any other relevant notes or explanations here. **Remove this line if you have nothing to add.**

## Reviews Required
* [x] Dev
* [ ] Test
* [ ] Tech Author
* [ ] Product Owner

## Review Checklist
:information_source: This section is to be filled in by the **reviewer**.

* [ ] I have reviewed the changes in this PR and they fill all or part of the acceptance criteria of the ticket, and the code is in a mergeable state.
* [ ] If there were infrastructure, operational, or build changes, I have made sure there is sufficient evidence that the changes will work.
* [ ] I have ensured the changelog has been updated by the submitter, if necessary.

2023-06-21 17:15 UTC, matt-mercer requested changes

2023-06-21 17:15 UTC, matt-mercer commented on specification/mesh-api.yaml
> +    | MESH Python client ([GitHub repo](https://github.com/NHSDigital/mesh-client) \| [Python Package Index](https://pypi.org/project/Mesh-Client/)) | A sample client app written in Python. This is n
for the Python client 
rather than saying 'sample client app' ..  can we say 'a fully featured python client library' ...
...
it's definitely not a sample app, it's in production use by multiple mesh client users)
published in PyPi etc .. 

"This is not the same as the MESH Java client" is probably redundant ..

2023-06-21 17:15 UTC, matt-mercer commented on specification/mesh-api.yaml
> +    | MESH sandbox ([GitHub repo](https://github.com/NHSDigital/mesh-sandbox) \| [Python Package Index](https://pypi.org/project/mesh-sandbox/)) | For early developer testing, a realistic MESH experi
for sandbox we're saying "For more details, see 'Environments and testing' below." .. is that suggesting that details on the sandbox should be mentioned in environments and testing ? ( as there are no changes below ) ..

2023-06-21 17:18 UTC, tonyheap commented on specification/mesh-api.yaml
> +    | MESH sandbox ([GitHub repo](https://github.com/NHSDigital/mesh-sandbox) \| [Python Package Index](https://pypi.org/project/mesh-sandbox/)) | For early developer testing, a realistic MESH experi
they already are

2023-06-21 17:18 UTC, tonyheap commented on specification/mesh-api.yaml
> +    | MESH Python client ([GitHub repo](https://github.com/NHSDigital/mesh-client) \| [Python Package Index](https://pypi.org/project/Mesh-Client/)) | A sample client app written in Python. This is n
will do

2023-06-22 07:25 UTC, tonyheap commented on specification/mesh-api.yaml
> +    | MESH Python client ([GitHub repo](https://github.com/NHSDigital/mesh-client) \| [Python Package Index](https://pypi.org/project/Mesh-Client/)) | A sample client app written in Python. This is n
Done

2023-06-22 09:20 UTC, matt-mercer approved these changes

2023-06-22 09:22 UTC, merged